In [11]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Unindo dados de todos os integrantes do grupo em um único DataFrame

In [12]:
my_list = [
    '../dados/GabrielKoji/MyListKoji.csv',
    '../dados/JoãoVargas/MyListJoao.csv',
    '../dados/RafaelCruz/MyListRafa.csv',
    '../dados/RaissaCasale/MyListRaissa.csv',
    '../dados/RyanLionel/MyListRyan.csv'
]

df_mylist = pd.concat([pd.read_csv(f) for f in my_list], ignore_index=True)

display(df_mylist.head(5))

  Profile Name Country Utc Title Add Date                          Title Name
0        Extra  Brazil         2025-12-13                       Kamisama Kiss
1        Extra  Brazil         2025-10-05               Is It Cake? Halloween
2        Extra  Brazil         2025-08-19  Elize Matsunaga: Once Upon a Crime
3        Extra  Brazil         2025-08-06                               Elite
4        Extra  Brazil         2025-05-11                           Soul Mate

In [26]:
viewing = [
    '../dados/GabrielKoji/ViewingActivityKoji.csv',
    '../dados/JoãoVargas/ViewingActivityJoao.csv',
    '../dados/RafaelCruz/ViewingActivityRafa.csv',
    '../dados/RaissaCasale/ViewingActivityRaissa.csv',
    '../dados/RyanLionel/ViewingActivityRyan.csv'
]

df_viewing = pd.concat([pd.read_csv(f) for f in viewing], ignore_index=True)

df_filtrado = df_viewing[df_viewing["Start Time"] > "2023-11-20"]

display(df_filtrado)

df_filtrado.to_csv('ViewingActivityAll.csv', index=False)

,Duration,Start Time,Profile Name,Country,Bookmark,Latest Bookmark,Supplemental Video Type,Attributes,Device Type,Title
0,00:00:05,2026-01-30 14:59:45,Extra,BR (Brazil),00:56:20,00:56:20,NaN,NaN,DefaultWidevineAndroidPhone,Bridgerton: Temporada 1: Diamante raro (episód...
1,00:05:47,2026-01-30 14:39:46,Extra,BR (Brazil),00:54:40,Not latest view,NaN,NaN,DefaultWidevineAndroidPhone,Bridgerton: Temporada 1: Diamante raro (episód...
2,00:40:58,2026-01-30 09:18:13,Extra,BR (Brazil),00:40:09,Not latest view,NaN,NaN,DefaultWidevineAndroidPhone,Bridgerton: Temporada 1: Diamante raro (episód...
3,00:00:38,2026-01-30 08:40:42,Extra,BR (Brazil),00:25:59,00:25:59,NaN,NaN,DefaultWidevineAndroidPhone,Bridgerton: Temporada 4: Um Perfeito Cavalheir...
4,00:06:37,2026-01-30 01:26:09,Extra,BR (Brazil),00:20:14,00:20:14,NaN,NaN,Chrome OS (Cadmium),Dr. House: Temporada 5: Simple Explanation (ep...
...,...,...,...,...,...,...,...,...,...,...
95303,01:09:17,2023-12-02 23:54:14,Ryan,BR (Brazil),01:09:19,Not latest view,NaN,NaN,LG 2017 LG M16p Standard UHD TV Smart TV,Encontro Fatal
95304,01:48:12,2023-12-01 21:11:24,Ryan,BR (Brazil),01:48:12,01:48:12,NaN,NaN,LG 2017 LG M16p Standard UHD TV Smart TV,Próxima Parada: Apocalipse
95305,01:25:23,2023-12-01 19:34:13,Ryan,BR (Brazil),01:25:23,01:25:23,NaN,Autoplayed: user action: User_Interaction,,"LG 2017 LG M16p Standard UHD TV Smart TV,Um Lugar"
95306,01:10:02,2023-11-29 00:29:44,Ryan,BR (Brazil),01:10:02,01:10:02,NaN,Autoplayed: user action: User_Interaction,,"LG 2017 LG M16p Standard UHD TV Smart TV,Paral..."
95307,01:09:25,2023-11-25 01:09:34,Ryan,BR (Brazil),01:09:25,01:09:25,NaN,NaN,LG 2017 LG M16p Standard UHD TV Smart TV,História de um Crime: O Cabeleireiro das Estrelas