# Notebook - ETL
#### O objetivo deste notebook é juntar e padronizar os dados dos .csvs necessários para a análise, para que possam ser consumidos no Power BI

## 0 - Importações

In [5]:
import pandas as pd

## 1 - Unindo os dados de todos os integrantes do grupo em um único DataFrame

In [6]:
my_list = [
    '../dados/GabrielKoji/MyListKoji.csv',
    '../dados/JoãoVargas/MyListJoao.csv',
    '../dados/RafaelCruz/MyListRafa.csv',
    '../dados/RaissaCasale/MyListRaissa.csv',
    '../dados/RyanLionel/MyListRyan.csv'
]

df_mylist = pd.concat([pd.read_csv(f) for f in my_list], ignore_index=True)

display(df_mylist.head(5))

  Profile Name Country Utc Title Add Date                          Title Name
0        Extra  Brazil         2025-12-13                       Kamisama Kiss
1        Extra  Brazil         2025-10-05               Is It Cake? Halloween
2        Extra  Brazil         2025-08-19  Elize Matsunaga: Once Upon a Crime
3        Extra  Brazil         2025-08-06                               Elite
4        Extra  Brazil         2025-05-11                           Soul Mate

In [7]:
viewing = [
    '../dados/GabrielKoji/ViewingActivityKoji.csv',
    '../dados/JoãoVargas/ViewingActivityJoao.csv',
    '../dados/RafaelCruz/ViewingActivityRafa.csv',
    '../dados/RaissaCasale/ViewingActivityRaissa.csv',
    '../dados/RyanLionel/ViewingActivityRyan.csv'
]

df_viewing = pd.concat([pd.read_csv(f) for f in viewing], ignore_index=True)

display(df_viewing)

,Duration,Start Time,Profile Name,Country,Bookmark,Latest Bookmark,Supplemental Video Type,Attributes,Device Type,Title
0,00:00:05,2026-01-30 14:59:45,Extra,BR (Brazil),00:56:20,00:56:20,NaN,NaN,DefaultWidevineAndroidPhone,Bridgerton: Temporada 1: Diamante raro (episód...
1,00:05:47,2026-01-30 14:39:46,Extra,BR (Brazil),00:54:40,Not latest view,NaN,NaN,DefaultWidevineAndroidPhone,Bridgerton: Temporada 1: Diamante raro (episód...
2,00:40:58,2026-01-30 09:18:13,Extra,BR (Brazil),00:40:09,Not latest view,NaN,NaN,DefaultWidevineAndroidPhone,Bridgerton: Temporada 1: Diamante raro (episód...
3,00:00:38,2026-01-30 08:40:42,Extra,BR (Brazil),00:25:59,00:25:59,NaN,NaN,DefaultWidevineAndroidPhone,Bridgerton: Temporada 4: Um Perfeito Cavalheir...
4,00:06:37,2026-01-30 01:26:09,Extra,BR (Brazil),00:20:14,00:20:14,NaN,NaN,Chrome OS (Cadmium),Dr. House: Temporada 5: Simple Explanation (ep...
...,...,...,...,...,...,...,...,...,...,...
108413,00:00:30,2015-12-04 08:56:45,Ryan,BR (Brazil),00:13:20,00:13:20,NaN,NaN,Mobile,Zé Colmeia: O Filme
108414,00:00:55,2015-12-04 08:55:16,Ryan,BR (Brazil),00:29:19,Not latest view,NaN,NaN,Mobile,Os Pinguins de Madagascar – O Filme
108415,00:07:48,2015-12-04 08:45:39,Ryan,BR (Brazil),00:00:23,Not latest view,NaN,NaN,Mobile,Toy Story 2
108416,00:05:08,2015-12-04 08:39:27,Ryan,BR (Brazil),00:00:00,Not latest view,NaN,NaN,Mobile,Toy Story 3
108417,00:07:34,2015-12-03 22:45:28,Ryan,BR (Brazil),00:07:34,Not latest view,NaN,NaN,Mobile,Hermanoteu na Terra de Godah

## 2 - Exportando os DataFrames transformados para a pasta dados-transformados

In [9]:
df_mylist.to_csv('../dados-transformados/MyList.csv', index=False)
df_viewing.to_csv('../dados-transformados/Viewing.csv', index=False)